version: '3.9'
services:
  poetbot:
    image: mritd/poetbot
    container_name: poetbot
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone
      - data:/data
    environment:
      - POETBOT_APPID
      - POETBOT_APPHASH
    #entrypoint: ["bash","-c","sleep 9999999"]
volumes:
  data:
