version: '3.7'
services:
  zk1:
    image: zookeeper:3.5.5
    container_name: zk1
    restart: always
    hostname: zk1
    volumes:
      - zk1_data:/data
      - zk1_log:/datalog
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk2:
    image: zookeeper:3.5.5
    container_name: zk2
    restart: always
    hostname: zk2
    volumes:
      - zk2_data:/data
      - zk2_log:/datalog
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk3:
    image: zookeeper:3.5.5
    container_name: zk3
    restart: always
    hostname: zk3
    volumes:
      - zk3_data:/data
      - zk3_log:/datalog
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

volumes:
  zk1_data:
  zk2_data:
  zk3_data:
  zk1_log:
  zk2_log:
  zk3_log:
