version: '3.7'
services:
  verdaccio:
    image: mritd/verdaccio:v3.10.2
    container_name: verdaccio
    restart: unless-stopped
    init: true
    volumes: 
      - data:/verdaccio
    ports:
      - "4873:4873"
volumes:
  data:
