version: '3.7'
services:
  pmm:
    image: percona/pmm-server:2.3.0
    container_name: pmm
    restart: unless-stopped
    volumes:
      - data:/srv
    ports:
      - "80:80"
      - "443:443"
volumes:
  data:
