version: '3'
services:
  taiga-front:
    image: taiga-front
    container_name: taiga-front
    restart: always
    volumes:
      - "./conf/conf.json:/usr/local/taiga-front/dist/conf.json"
      - "./conf/nginx/ssl:/etc/nginx/ssl"
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"
      - "./conf/nginx/log:/var/log/nginx"
      - "data:/data"
    ports:
      - "80:80"
      - "443:443"
  taiga-back:
    image: taiga-back
    container_name: taiga-back
    restart: always
    volumes:
      - "./conf/local.py:/usr/local/taiga-back/settings/local.py"
      - "data:/data"
  taiga-events:
    image: taiga-events
    container_name: taiga-events
    restart: always
    volumes:
      - "./conf/config.json:/usr/local/taiga-events/config.json"

volumes:
  data:
